### ISSUE TITLE
Play Command Not working :(

### ISSUE THREAD

**Issue by kushal81** [Tomato6966/Milrato-x-Rythm#10]
**The bot is online and it's working but it's play command not working** 
![IMG_20211010_225420](https://user-images.githubusercontent.com/83442979/136706663-51319d7b-020e-4da9-9e96-5b5d9d9a8060.jpg)

# TOMATO / ANYONE PLS HELP ME IN THIS SITUATION @Tomato6966 

EVEN THO I AM IN SUPPORT SERVER ASKING HELP BUT YEA NO ONE HELPS :( ....... SO PLS RESPOND ME I NEED THE HELP.

**Comment by kushal81** [comment]
ANY ONE HELP ME PLS I BEG U GUYS

**Comment by Tomato6966** [comment]
start lavalink
