### ISSUE TITLE
Issue On the DataBase

### ISSUE THREAD

**Issue by saivarshithm** [Tomato6966/Milrato-x-Rythm#7]
- @Tomato6966 Can u change the database from quick.db to quickmongo

**Comment by Bedrock16** [comment]
Why? Can I know

**Comment by saivarshithm** [comment]
> Why? Can I know

We Can Easy Can Store Mre data

**Comment by Bedrock16** [comment]
Database is stored in database folder and I don't think that it will affect anything . If you want you can use quickmongo too but I don't think Tomato will agree on this because he use quick.db on every bot he made .

**Comment by Tomato6966** [comment]
Why should I change the database to something worse?
Enmap uses sqlite
quick mongo uses sqlite

why enmap?
+ Secure, saves data and doesnt corrupt
+ Multiple Files, multiple Directories
+ More features and faster
+ Synchronus

Why not quick.db?
- insecure
- slow
- corrupts often

**Comment by rilysh** [comment]
> 

Quickmongo is nothing else than a wrapper of mongodb client for Nodejs. It uses same JSON based data saving using specific key and data. Where if I compare enmap in this way,  it's worst, as it doesn't support sharding, requires extra storage for storing data, not secure (doesn't uses any pointed encryption), asynchronous is more better rather stuck in synchronous.
There's no meaning to use it except for own Discord server (limited members either for testing purposes) same to quickdb as well.
